sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
  - secure: Pz191NttgM9jeaHTu37lAmRY6E3xBfYMVc/+DhOb9AkrIz15kr5rgnM77OpcRvy9Mg3OdgCmi3ZqWEcJvwaakQlADWGxFIXkJw/E4asg7OkPZM9cLktgZeNcYARqUVUt9KNcH0G/gk57RCpyznahAdFVgEoI9Qv+rybT/puOy2g3DNl3zaZ4JmbZvpLnKNjGSNLvnMjmSN4qE2uy4BRTYLrNPBsRfhr7+45YXVaaSVf1xFIvvY9/Ljy8Y/4rxH495wwexi08YzolKO2O+LPLnR1TtIOAQx8B9LoLAikDiH0Zw0B+nKKD+1AiyQL+btp16tNZ04XlGvy8NWx8QN4JfTxDEJmESBV9eVVhAVkAxGCFkb8i8DRJo21z7zr2V8arPQURy+0dsQ+dAdIdRDnO/CuNEh/fP7AIYJvuKdyzWNpCMIWr/iT+taF50/4RCjl4kYXGrwRRrI/MVPjrbOE7IUU219tZFuDOjWnu1RKR7J0TLkJckyelJrl58sDxONiCK54rxvqM6aJL/yZRJ/lv4XDQMXaqhl0LtmtVR95SvBbpjlOL+Op/YWWnd7NucZ56hars4qpSRm4i8U7jLEubIAmFxu/P2M//MWuqPi24jNe0llxgVIhP/fDugDufRvM70FKFvgDWDULPV4J/V9UD6vxITGqJi6E0F9+Z+eldbVM=
branches:
  only:
    - master